#ifndef __HSPSDK_PACKAGE_INFO_H__
#define __HSPSDK_PACKAGE_INFO_H__

#define HSPSDK_SUPPORTS_CORE
#define HSPSDK_SUPPORTS_PAYMENT
#define HSPSDK_SUPPORTS_ITEMDELIVERY
#define HSPSDK_SUPPORTS_PROMOTION

#endif // __HSPSDK_PACKAGE_INFO_H__
